version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/seike460/caws
    steps:
      - checkout
      - run: go vet ./...
      - run: go get -v -t -d ./...
      - run: go test -coverprofile=cover.out -v ./...
      - run: go tool cover -html=cover.out -o cover.html
      - store_artifacts:
          path: coverage.html
          destination: coverage.html
